### ISSUE TITLE
例子里是单独的 asp .net core作为服务端,为什么不可以直接在Unity做服务端呢

### ISSUE THREAD

**Issue by kane9527-e** [MonoLogueChi/unity-grpc-demo#1]

**Comment by MonoLogueChi** [comment]
为什么要使用unity作为服务端？

**Comment by kane9527-e** [comment]
可以做局域网房间游戏啊,例如我在开发一款射击馆的比赛游戏,可以自己开房间或者其他人开房间,别人加入房间后比赛等,不想用udp广播也不想增加运维成本单独写个服务端.之前的 grpc core c核心的版本是可以的, .net版本貌似是因为依赖注入等一堆问题我是没搞明白,还请赐教.

**Comment by kane9527-e** [comment]
之前看过Unet和mirror这类网络库,我感觉对于我做的项目太大材小用了,毕竟还是有这方便需求,但又不需要那么庞大繁杂的网络库Grpc是最好的选择

**Comment by MonoLogueChi** [comment]
Grpc.AspNetCore.Server 不支持 .net standard 2.1 或2.0

**Comment by kane9527-e** [comment]
好吧 感谢.看来只能等待Unity支持.net core clr了
